### ISSUE TITLE
Resize error when saving the plot from the buffer

### ISSUE THREAD

**Issue by Chevrefeuille** [lverret/findfunc#1]
When I run any of the provided files, I get the following error

```
    z = z.reshape((nrows, ncols, 3))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 2304000 into shape (400,480,3)
```

This is because the size of the array obtained from the `np.frombuffer()` function does not match with the size of the canvas obtained with `get_width_height()` (it is somehow 4 times bigger,  2304000 = 400x480x3x4).

It seems to be related to [this question](https://stackoverflow.com/questions/67601709/fig-canvas-tostring-rgb-output-wrong-length-bytes-but-only-on-windows) on stackoverflow. It can be solved by adding
```
import matplotlib

matplotlib.use("agg")
```

before the import of `pyplot`.

Another way to solve this would be to use [FuncAnimation](https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.FuncAnimation.html) which also allows to save as a gif.

**Comment by lverret** [comment]
Thanks for the feedback.
I've revamped the .gif generation based on your suggestion.
